name: Run Python Script Every Hour

on:
  schedule:
    - cron: '0 * * * *'  # Every hour (UTC time)
  workflow_dispatch:      # Allow manual run

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Set the Python version you want to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: |
          python trial.py  # Replace with the name of your Python script
